# fly.toml app configuration file generated for twilio-whatsapp-chatbot-service on 2023-11-16T00:01:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twilio-whatsapp-chatbot-service"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5002"
  LOG_LEVEL = "debug"
  FLASK_DEBUG = 1

[http_service]
  internal_port = 5002
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
